// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbawfmjwagirqpiiofxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndiYXdmbWp3YWdpcnFwaWlvZnh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzODY1MzIsImV4cCI6MjA1ODk2MjUzMn0.SSCqmhH2utWKjeypfs-EWONc3E-3gQOi_u1poLiOh5g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);